---
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/youcef/docker_app/libreoffice/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
